---
exp_name: BiGG
exp_dir: exp/BiGG
#device: cuda:0
device: cpu
gpu: -1
seed: 1234
dataset:
  name: top10
  data_path: data/
  directed: false
  self_loop: false
  bfs_permute: false
model:
  name: BiGG
  max_num_nodes: 743
  embed_dim: 256
  num_RNN_layers: 2
  bits_compress: 256
  tree_pos_enc: false
  pos_enc: true
  pos_base: 10000
  greedy_frac: 0.0
  share_param: true
  blksize: -1
train:
  batch_size: 32
  optimizer: Adam
  lr: 3.0e-4
  grad_clip: 5
  accum_grad: 1
  max_epochs: 1000
  display_iter: 10
  snapshot_epoch: 1000
  resume: false
  resume_epoch: null
  resume_model_dir: exp/BiGG/BiGG_cora_2021-Feb-25-10-38-59_12345
  resume_model_name: epoch-1000.ckpt
test:
  num_test_gen: 10
  display: false
  load_snapshot: false
  test_model_dir: exp/BiGG/BiGG_cora_2021-Feb-25-10-38-59_12345
  test_model_name: epoch-1000.ckpt
