---
exp_name: BiGG
exp_dir: exp/BiGG
device: cuda:2
#device: cpu
gpu: 2
seed: 1234
dataset:
  name: top10
  data_path: data/
  directed: false
  self_loop: false
  bfs_permute: false
model:
  name: BiGG
  max_num_nodes: 743
  embed_dim: 256
  num_RNN_layers: 2
  bits_compress: 256
  tree_pos_enc: false
  pos_enc: true
  pos_base: 10000
  greedy_frac: 0.0
  share_param: true
  blksize: -1
train:
  batch_size: 32
  optimizer: Adam
  lr: 3.0e-4
  grad_clip: 5
  accum_grad: 1
  max_epochs: 100
  display_iter: 10
  save_snapshot: false
  snapshot_epoch: 100
  resume: false
  resume_epoch: 99
  resume_model_dir: exp/BiGG/BiGG_top10_2021-Mar-15-19-44-39_115041
  resume_model_name: epoch-100.ckpt
test:
  num_test_gen: 10
  greedy_frac: 0.0
  display: false
  load_snapshot: false
  test_model_dir: exp/BiGG/BiGG_top10_2021-Mar-15-19-44-39_115041
  test_model_name: epoch-100.ckpt
eval:
  num_nodes: [100, 1000, 10000, 100000, 1000000]
  graph_type: W-S # selected from [E-R, B-A, W-S, grid]