---
exp_name: BiGG
exp_dir: exp/BiGG
device: cuda:0
gpu: 1
#device: cpu
seed: 1234
dataset:
  name: top10
  data_path: data/
  directed: false
  self_loop: false
  bfs_permute: false
model:
  name: BiGG
  max_num_nodes: 743
  embed_dim: 256
  num_RNN_layers: 2
  bits_compress: 256
  position_encoding: true
  position_base: 10000
  share_param: true
  blksize: -1
train:
  optimizer: Adam
  lr: 1.0e-2
  gradient_clip: 5
  max_epochs: 1000
  display_iter: 10
  snapshot_epoch: 1000
#test:
#  test_model_dir: exp/VGAE/VGAE_cora_2021-Feb-25-10-38-59_12345
#  test_model_name: model_snapshot_0001000.pth
