---
exp_name: SBMGNN_DD
exp_dir: exp/SBMGNN_DD
seed: 28517
gpu: 1
device: cuda:0
dataset:
  name: _graph_0
  data_path: data/
  features: false
model:
  name: SBMGNN
  hidden: [64, 50]
  num_nodes: 53
  g_hidden: 32
  deep_decoder: 1
  dropout: 0.5
  alpha0: 10.
  temp_prior: 0.5
  temp_post: 1.
  variational: false
train:
  lr: 0.01
  max_epochs: 150
  weight_decay: 0.0
  use_k_fold: false
  k: 5
  early_stopping: 0
  split_idx: 0
  weighted_ce: 1
  reconstruct_x: false
