---
exp_name: Template_name
exp_dir: exp/Template
device: cuda:0
gpu: 1
#device: cpu
seed: 1234
dataset:
  name: Template_data
  data_path: data/
model:
  name: Template_model
  num_nodes: 1000
  embedding_dim: 32
  hidden_dim: 32
train:
  optimizer: Adam
  lr: 1.0e-2
  max_epochs: 1000
  display_iter: 10
  snapshot_epoch: 1000
test:
  test_model_dir: exp/Template_name/Template_model_Template_data_2021-Feb-25-10-38-59_12345
  test_model_name: model_snapshot_0001000.pth
