---
exp_name: VGAE
exp_dir: exp/VGAE
device: cuda:1
gpu: 1
#device: cpu
seed: 1234
dataset:
  name: top10
  data_path: data/
model:
  name: VGAE
  num_nodes: 100000
  embedding_dim: 32
  hidden_dim: 32
  variational: false
  has_feature: false
  num_GNN_layers: 2
train:
  optimizer: Adam
  lr: 1.0e-2
  max_epochs: 100
  display_iter: 10
  snapshot_epoch: 1000
#test:
#  test_model_dir: exp/VGAE/VGAE_cora_2021-Feb-25-10-38-59_12345
#  test_model_name: model_snapshot_0001000.pth
eval:
  num_nodes: [100, 1000, 10000, 100000, 1000000]
  graph_type: W-S # selected from [E-R, B-A, W-S, grid]