---
exp_name: Graphite_FIRST
exp_dir: exp/Graphite_FIRST
device: cuda:0
gpu: 1
#device: cpu
seed: 19987
dataset:
  name: FIRSTMM_DB_graph_10
  data_path: data/
model:
  name: Graphite
  num_nodes: 
  embedding_dim: 256
  hidden_dim: 512
  decoding_dim: 256
  variational: true
  has_feature: false
train:
  optimizer: Adam
  lr: 1.0e-2
  max_epochs: 500
  display_iter: 10
  snapshot_epoch: 1000
#test:
#  test_model_dir: exp/VGAE/VGAE_cora_2021-Feb-25-10-38-59_12345
#  test_model_name: model_snapshot_0001000.pth
